project:
  type: book

book:
  title: "phcco"
  author: "Norah Jones"
  date: "5/20/2024"
  chapters:
    - index.qmd
    - UriAlon1.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

