project:
  type: book

book:
  title: "PHCCO"
  author: "Karthik"
  date: "5/20/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - UriAlon1.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

